- name: "controlPlane_multiple_niova_block_test.yml"
  hosts: localhost
  connection: local
  vars:
    recipe_name: "controlPlane_multiple_niova_block_test"
    user_name: "admin"
    user_secret: "test-admin-secret-123"
    nisd_root_keys:
              - "/nisd_root_entry/0/uuid"
              - "/nisd_root_entry/0/instance-uuid"
              - "/nisd_root_entry/0/status"
              - "/nisd_root_entry/0/num-reserved-pblks"
              - "/nisd_root_entry/0/num-pblks"
              - "/nisd_root_entry/0/num-pblks-used"
              - "/nisd_root_entry/0/vblks-written"
              - "/nisd_root_entry/0/vblks-written"
              - "/nisd_root_entry/0/num-pblks-used"
              - "/nisd_root_entry/0/num-reserved-pblks-used"
    parent: None

  tasks:
    - block:
        # check for the app_type
        - name: "{{ recipe_name }}: Check if the app_type is 'controlplane'."
          vars:
            app_type: "{{ app_type }}"
          debug:
            msg: "app_type is: {{ app_type }}"
          failed_when: (app_type != "controlplane")

        - name: "{{ recipe_name }}: Start PMDB cluster and fetch membership"
          include_role:
            name: common
            tasks_from: start_pmdb_and_get_membership.yml

        - name: Get NIOVA_BIN_PATH
          set_fact:
            niova_bin_path: "{{ lookup('env', 'NIOVA_BIN_PATH') }}"

        - name: "{{ recipe_name }}: Run controlplane Go test to create entity hierarchy."
          vars:
            input_param:
              test_path: "{{ niova_bin_path }}/ctlplane_test"
              test_name: "TestCreateHierarchyForMultipleBlockTest"
              output_file: "go_test_output"
          set_fact:
            gotest_result: "{{ lookup('controlplane', 'gotest', input_param) }}"

        - name: "{{ recipe_name }}: Print go test result."
          debug:
            msg: "{{ gotest_result }}"

        - name: "{{ recipe_name }}: Verify all Go tests passed."
          vars:
            failed_tests: "{{ gotest_result.parsed_results.failed }}"
          debug:
            msg: "Number of failed tests: {{ failed_tests }}"
          failed_when: (failed_tests | int) > 0

        # NOTE: For testing in CI, only one nisd is used
        - name: Extract NISD UUID
          set_fact:
            nisd_uuids: >-
              {{
                gotest_result.parsed_results.tests[0].info_messages
                | select('search', 'Nisd ID')
                | map('regex_replace', '.*Nisd ID: ', '')
                | list
              }}

        - name: "{{ recipe_name }}: Print the nisd list."
          debug: 
            msg: "{{ nisd_uuids }}"

        - name: "{{ recipe_name }}: Run controlplane Go test to create vdevs."
          vars:
            input_param:
              test_path: "{{ niova_bin_path }}/ctlplane_test"
              test_name: "TestUserVdevCreationForMultipleBlockTest"
              output_file: "go_test_output_1"
          set_fact:
            gotest_result_1: "{{ lookup('controlplane', 'gotest', input_param) }}"

        - name: "{{ recipe_name }}: Print go test 1 result."
          debug:
            msg: "{{ gotest_result_1 }}"

        - name: "{{ recipe_name }}: Verify all Go tests passed."
          vars:
            failed_tests: "{{ gotest_result_1.parsed_results.failed }}"
          debug:
            msg: "Number of failed tests: {{ failed_tests }}"
          failed_when: (failed_tests | int) > 0

        - name: Extract Vdev UUIDs
          set_fact:
            vdev_uuids: >-
              {{
                gotest_result_1.parsed_results.tests[0].info_messages
                | select('search', 'Vdev ID')
                | map('regex_replace', '.*Vdev ID: ', '')
                | list
              }}

        - name: "{{ recipe_name }}: Print the vdev list."
          debug: 
            msg: "{{ vdev_uuids }}"

        # NOTE: For testing in CI, only 1 device is created
        - name: "{{ recipe_name }}: create multiple nisd devices"
          vars:
            img_dir: "/auth_nisd_{{ item }}.device"
            bs: "1G"
          debug:
            msg: >-
              {{
                lookup('helper', 'create_dd_file', img_dir, bs, 24)
              }}
          loop: "{{ range(0, 1) | list }}"
          register: nisd_dev_paths

        - name: Extract device paths
          set_fact:
            nisd_devices: "{{ nisd_dev_paths.results | map(attribute='msg') | list }}"

        - name: "{{ recipe_name }}: Print device paths."
          debug:
            msg: "{{ nisd_devices }}"

        - name: "{{ recipe_name }}: Start niova-block-ctl process for all devices"
          vars:
            input_param: {
              'nisd_device_path': "{{ item.0 }}",
              'nisd_uuid': "{{ item.1 }}"
            }
          debug:
            msg: "{{ lookup('nisd_handler', 'run-niova-block-ctl', input_param) }}"
          loop: "{{ (nisd_devices | zip(nisd_uuids) | list) }}"
          register: niova_block_ctl_results

        - name: "{{ recipe_name }}: Print niova-block-ctl result."
          debug: 
            msg: "{{ niova_block_ctl_results }}"
    
        - name: "{{ recipe_name }}: Start all nisds"
          vars:
            input_param: {
              'nisd_device_path': '{{ item.0 }}',
              'nisd_uuid': '{{ item.1 }}',
              'peer_port': '{{ 13000 + (idx*2) }}',
              'client_port': '{{ 13000 + (idx*2) + 1 }}',
              'enable_auth': 1,
            }
          debug:
            msg:
              - "{{ lookup('nisd_handler', 'run_nisd', input_param) }}"
          loop: "{{ (nisd_devices | zip(nisd_uuids) | list) }}"
          loop_control:
            index_var: idx
            label: "{{ item.0 }} -> {{ item.1 }} (peer={{ 13000 + (idx * 2) }}, client={{ 13000 + (idx * 2) + 1 }})"
          register: nisd_start_results

        # - name: "{{ recipe_name }}: Wait for nisd to get updated."
        #   vars:
        #     stage: "wait_for_nisd_root_entry"
        #     lookout_uuid: ""
        #   debug:
        #     msg: "Waiting for nisd to get updated"
        #   until: lookup('niova_ctlrequest', 'lookup', item, "/nisd_root_entry/0/status", 'nisd', lookout_uuid) | dict2items | map(attribute='value') | list | first == "running"
        #   retries: 10
        #   delay: 1
        #   loop: "{{ nisd_uuids }}"
        #   loop_control:
        #     label: "Checking {{ item }}"

        - name: "{{ recipe_name }}: Print nisd results."
          debug: 
            msg: "{{ nisd_start_results }}"

        - name: "{{ recipe_name }}: wait for 5 seconds"
          pause:
            seconds: 5

        - name: "{{ recipe_name }}: Start niova-block-test process."
          vars:
            input_param: {
                 'auth_username': '{{ user_name }}',
                 'auth_secret': '{{ user_secret }}',
                 'vdev' : '{{ item }}',
                 'rd_op_ratio': '0',
                 'num_ops': '50',
                 'random_seed_pt': '123',
                 'request_size_in_bytes': '0',
                 'integrity_check': 'False',
                 'sequential_writes': 'False',
                 'blocking_process': 'False'
            }
          debug:
            msg: "{{ lookup('nisd_handler', 'niova-block-test', input_param) }}"
          loop: "{{ vdev_uuids }}"
          register: nblock_test_results

        - debug:
            msg: "{{ nblock_test_results }}"

      rescue:
        - name: "Recipe: {{ recipe_name }} failed"
          set_fact:
            terminate_recipe: true  