- name: "controlPlane_entity_filter_support.yml"
  hosts: localhost
  connection: local
  vars:
    recipe_name: "controlPlane_entity_filter_support"
    parent: None

  tasks:
    - block:
        # check for the app_type
        - name: "{{ recipe_name }}: Check if the app_type is 'controlplane'."
          vars:
            app_type: "{{ app_type }}"
          debug:
            msg: "app_type is: {{ app_type }}"
          failed_when: (app_type != "controlplane")

        - name: "{{ recipe_name }}: Start pmdb and proxy servers."
          include_role:
            name: common
            tasks_from: pmdb_cluster_init.yml
          vars:
            number_of_clients: 2
            number_of_PMDBServers: 5

        - name: "{{ recipe_name }}: Starting controlplane_client to get membership details."
          vars:
            input_param:
              { "Operation": "membership", "OutfileName": "membership_output" }
            ncpclires: "{{ lookup('controlplane', 'ncpc', input_param) }}"
          debug:
            msg: "get membership details of running servers."
          with_items:
            - "{{ ncpclires }}"
          register: membership
          no_log: True

        - name: "{{ recipe_name }}: Run controlplane Go test to create the test hierarchy."
          vars:
            input_param:
              # test_path: "/home/runner/work/niovad/niovad/build_dir/ctlplane_test"
              test_path: "/home/himani/niova-mdsvc/controlplane/ctlplanefuncs/client"
              test_name: "TestCreateLargeHierarchyForEntityFilters"
              output_file: "go_test_output_1"
          set_fact:
            gotest_result_1: "{{ lookup('controlplane', 'gotest', input_param) }}"

        - name: "{{ recipe_name }}: Print the go test 1 result."
          debug:
            msg: "{{ gotest_result_1 }}"

        - name: "{{ recipe_name }}: Verify all Go tests passed."
          vars:
            failed_tests: "{{ gotest_result_1.parsed_results.failed }}"
          failed_when: (failed_tests | int > 0)

        - name: "{{ recipe_name }}: Run controlplane Go test to create and validate vdevs with entity filters."
          vars:
            input_param:
              # test_path: "/home/runner/work/niovad/niovad/build_dir/ctlplane_test"
              test_path: "/home/himani/niova-mdsvc/controlplane/ctlplanefuncs/client"
              test_name: "TestCreateVdevWithFilters"
              output_file: "go_test_output_2"
          set_fact:
            gotest_result_2: "{{ lookup('controlplane', 'gotest', input_param) }}"

        - name: "{{ recipe_name }}: Print the go test 2 result."
          debug:
            msg: "{{ gotest_result_2 }}"

        - name: "{{ recipe_name }}: Verify all Go tests passed."
          vars:
            failed_tests: "{{ gotest_result_2.parsed_results.failed }}"
          failed_when: (failed_tests | int > 0)

        - name: "{{ recipe_name }}: Run controlplane Go test to create and validate vdevs with invalid entity filters."
          vars:
            input_param:
              # test_path: "/home/runner/work/niovad/niovad/build_dir/ctlplane_test"
              test_path: "/home/himani/niova-mdsvc/controlplane/ctlplanefuncs/client"
              test_name: "TestCreateVdevWithInvalidFilters"
              output_file: "go_test_output_3"
          set_fact:
            gotest_result_3: "{{ lookup('controlplane', 'gotest', input_param) }}"

        - name: "{{ recipe_name }}: Print the go test 3 result."
          debug:
            msg: "{{ gotest_result_3 }}"

        - name: "{{ recipe_name }}: Verify all Go tests passed."
          vars:
            failed_tests: "{{ gotest_result_3.parsed_results.failed }}"
          failed_when: (failed_tests | int > 0)

        - name: "{{ recipe_name }}: Run KV CRC verification script."
          debug:
            msg: "{{ lookup('kv_crc') }}"