- name: "controlPlane_vdev_test.yml"
  hosts: localhost
  connection: local
  vars:
    recipe_name: "controlPlane_vdev_test"
    parent: None

  tasks:
    - block:
        # check for the app_type
        - name: "{{ recipe_name }}: Check if the app_type is 'controlplane'."
          vars:
            app_type: "{{ app_type }}"
          debug:
            msg: "app_type is: {{ app_type }}"
          failed_when: (app_type != "controlplane")

        - name: "{{ recipe_name }}: Start PMDB cluster and fetch membership"
          include_role:
            name: common
            tasks_from: start_pmdb_and_get_membership.yml
          vars:
            number_of_clients: 2
            number_of_PMDBServers: 5

        - name: "{{ recipe_name }}: Run controlplane Go test to create vdev in parallel."
          vars:
            input_param:
              { 
                test_path: "/home/runner/work/niovad/niovad/build_dir/ctlplane_test",
                test_name: "TestCreateVdev",
                output_file: "go_test_output"
              }
          set_fact:
            gotest_result: "{{ lookup('controlplane', 'gotest', input_param) }}"

        - name: "{{ recipe_name }}: Print result."
          debug:
            msg: "{{ gotest_result }}"

        - name: "{{ recipe_name }}: Verify all Go tests passed."
          vars:
            failed_tests: "{{ gotest_result.parsed_results.failed }}"
          failed_when: (failed_tests | int > 0)

        - name: "{{ recipe_name }}: Run KV CRC verification script."
          debug:
            msg: "{{ lookup('kv_crc') }}"