- name: "tidb_setup"
  hosts: localhost
  connection: local
  vars:
    recipe_name: "tidb_setup"
    repo_path: "/mdsvc-tidb"
    api_base_url: "http://localhost:8081"
    infra_payload: "/home/himani/mdsvc-tidb/examples/e2e.json"
    vdev_payload: "/home/himani/mdsvc-tidb/examples/create_vdev_100gb_1replica.json"

  tasks:
    - block:

        # -----------------------------
        # 1. Create Infra
        # -----------------------------

        - name: Create infra
          set_fact:
            infra_result: "{{ lookup('tidb_api',
                'POST',
                '/infra',
                file=infra_payload,
                base_url=api_base_url) }}"

        - name: Debug infra response
          debug:
            var: infra_result

        # -----------------------------
        # 2. Create VDEV
        # -----------------------------
        
        - name: Create vdev
          set_fact:
            vdev_result: "{{ lookup('tidb_api',
                'POST',
                '/vdev',
                file=vdev_payload,
                base_url=api_base_url) }}"

        - name: Debug vdev result
          debug:
            msg: "{{ vdev_result }}"

        - name: Extract vdev UUID
          set_fact:
            vdev_uuid: "{{ vdev_result.vdev_id | default(vdev_result.uuid) }}"

        - name: Debug vdev UUID
          debug:
            msg: "Created VDEV UUID: {{ vdev_uuid }}"

        